name: List services in GCP
on:
  push:
      branches: [ "master" ]

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}


jobs:
  Get_OIDC_ID_token:
    name: Setup
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
